# Generated by Django 4.2.2 on 2023-06-19 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=8)),
                ('host_image_status', models.BooleanField(default=False)),
                ('join_image_status', models.BooleanField(default=False)),
                ('host_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('join_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('host_proximity', models.IntegerField(blank=True, null=True)),
                ('join_proximity', models.IntegerField(blank=True, null=True)),
                ('host_audio_status', models.BooleanField(blank=True, null=True)),
                ('join_audio_status', models.BooleanField(blank=True, null=True)),
                ('is_payment_done', models.BooleanField(default=False)),
                ('correlation', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room2_host', to=settings.AUTH_USER_MODEL)),
                ('join', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room2_join', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
