# Generated by Django 4.2.3 on 2023-07-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='payment_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
