# Generated by Django 4.2.2 on 2023-06-19 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstantRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=8)),
                ('user1_full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user1_gender', models.CharField(blank=True, choices=[('1', 'male'), ('2', 'female'), ('3', 'others')], max_length=1, null=True)),
                ('user1_date_of_birth', models.DateField(blank=True, null=True)),
                ('user2_full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user2_gender', models.CharField(blank=True, choices=[('1', 'male'), ('2', 'female'), ('3', 'others')], max_length=1, null=True)),
                ('user2_date_of_birth', models.DateField(blank=True, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('proximity', models.IntegerField(blank=True, null=True)),
                ('user1_audio_status', models.BooleanField(blank=True, null=True)),
                ('user2_audio_status', models.BooleanField(blank=True, null=True)),
                ('is_payment_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_host', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
