# Generated by Django 4.2.3 on 2023-07-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instantroom',
            name='payment_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
