# Generated by Django 4.2.3 on 2023-07-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instant', '0002_instantroom_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='instantroom',
            name='user_image_status',
            field=models.BooleanField(default=False),
        ),
    ]
